add_executable(checkpoint_rename_module_policyconvnet checkpoint_rename_module_policyconvnet.cpp)
target_link_libraries(checkpoint_rename_module_policyconvnet libpolicyts::libpolicyts)
target_compile_features(checkpoint_rename_module_policyconvnet PUBLIC cxx_std_23)

add_executable(checkpoint_rename_module_heuristicconvnet checkpoint_rename_module_heuristicconvnet.cpp)
target_link_libraries(checkpoint_rename_module_heuristicconvnet libpolicyts::libpolicyts)
target_compile_features(checkpoint_rename_module_heuristicconvnet PUBLIC cxx_std_23)

